### ISSUE TITLE
Feat: 결제페이지, 마이페이지 레이아웃 만들기

### ISSUE THREAD

**Issue by ewinkite** [Yanolza-Miniproject/frontend#11]
## Description
결제페이지, 마이페이지 레이아웃 만들기

## Todo

[결제페이지]
- [x] 결제 목록 아이템 컴포넌트 만들기
- [x] 약관 동의 컴포넌트 만들기
- [x] 전체 UI 제작

[마이페이지]
- [x] 전체 UI 제작

## ETC
마이페이지 내에서 찜/장바구니 목록을 일부 보여주는 방법 대신 진입점만 제공하는 방법으로 구현하였습니다.
추후 시간이 된다면 기존 안처럼 일부 보여줄 수 있도록 고도화시키고자 합니다.
