### ISSUE TITLE
Feat: 공통 컴포넌트 업데이트(Header)

### ISSUE THREAD

**Issue by mysdpy30s** [Yanolza-Miniproject/frontend#111]
## Description
공통 컴포넌트 업데이트

## Todo

- [x] Header - '숙소보기'(Category page) 메뉴 추가
- [x] Header - 로그인, 회원가입 메뉴 아이콘으로 변경
- [x] Header - 아이콘에 마우스 hover시 해당 메뉴 설명하는 툴팁 추가

## ETC
이 외에도 추가 필요한 부분 있으면 말씀주세요!
