### ISSUE TITLE
Feat: 마이페이지 닉네임 노출, 테스트 코드 업데이트, 사진 에러 처리 추가

### ISSUE THREAD

**Issue by ewinkite** [Yanolza-Miniproject/frontend#120]
## Description

마이페이지 닉네임 노출, 테스트 코드 업데이트, 사진 에러 처리 추가

## Todo

- [ ] 마이페이지 닉네임 노출
- [ ] 테스트 코드 업데이트
- [ ] 사진 에러 처리 추가

## ETC
-
