### ISSUE TITLE
Feat: 결제페이지, 결제내역 페이지 목업데이터 기반 로직 업데이트, 무한스크롤 구현

### ISSUE THREAD

**Issue by ewinkite** [Yanolza-Miniproject/frontend#18]
## Description
결제페이지, 결제내역 페이지 목업데이터 기반 로직 업데이트, 무한스크롤 구현

## Todo

- [x] 결제 페이지내 목업데이터 기반 로직 업데이트
- [x] 결제내역 페이지내 목업데이터 기반 로직 업데이트, 무한 스크롤 구현
- [x] 체크박스 공통 컴포넌트 적용

## ETC
-
