### ISSUE TITLE
 Refactoring: 코드리뷰 바탕으로 작성한 코드 리팩토링 (숙소상세/객실상세페이지)

### ISSUE THREAD

**Issue by suyeonnnnnnn** [Yanolza-Miniproject/frontend#184]
## Description
코드리뷰 바탕으로 작성한 코드 리팩토링 (숙소상세/객실상세페이지)

## Todo
- [ ] 페이지 반응형으로 수정
- [ ] 코드리뷰 바탕으로 작성한 코드 리팩토링 
- [ ] Readme.md 에러핸들링 & 회고 추가 작성하기
