### ISSUE TITLE
Feat: 기존 코드 수정, 메인페이지 msw 연결

### ISSUE THREAD

**Issue by mysdpy30s** [Yanolza-Miniproject/frontend#36]
## Description
기존 코드 수정 및 컴포넌트 단위 분할

## Todo
- [x] 기존 작성 코드 rem으로 단위 변경
- [x] 메인페이지 api 실제 url로 연동
- [x] 기타 배치 수정 및 일부 수정 작업
