### ISSUE TITLE
Chore: 카트 아이템, 좋아요 아이템, 결제 내역 아이템 목 데이터 작성

### ISSUE THREAD

**Issue by 2YH02** [Yanolza-Miniproject/frontend#4]
## Description
카트 아이템, 좋아요 아이템, 결제 내역 아이템 목 데이터 작성하기
(현재까지의 데이터 결정 상황에 맞춰 임시로 목 데이터 배열 생성)

## Todo

- [x] 카트 아이템 데이터 작성
- [x] 좋아요 아이템 데이터 작성
- [x] 결제 내역 아이템 데이터 작성

## ETC
상황에 따라 데이터가 바뀔 수 있습니다.
