### ISSUE TITLE
Refactoring: 검색페이지 컴포넌트 분할 및 코드 정리

### ISSUE THREAD

**Issue by mysdpy30s** [Yanolza-Miniproject/frontend#63]
## Description
검색페이지 컴포넌트 분할 및 코드 정리

## Todo
- [x] 검색페이지 상태 변수 관리
- [x] 검색 selector 컴포넌트 분할
- [x] 기타 에러 있을시 수정
