### ISSUE TITLE
Feat : 카테고리 페이지 생성 및 무한 스크롤 구현

### ISSUE THREAD

**Issue by LikeFireAndSky** [Yanolza-Miniproject/frontend#8]
## Description
카테고리 페이지 생성 및 무한 스크롤 구현

## Todo

- [x] 카테고리 routing 생성
- [x] 카테고리 페이지 검색바, 및 UI 기본 틀 구현
- [x] 무한 스크롤 구현
