### ISSUE TITLE
Feat : 메인페이지 UI 작성

### ISSUE THREAD

**Issue by mysdpy30s** [Yanolza-Miniproject/frontend#9]
## Description
메인페이지 UI 작성

## Todo
- [x] Header 아이콘 추가
- [x] 메인페이지 리스트 목업 데이터 추가
- [x] 메인페이지 레이아웃 추가

## ETC
- 기존 작성 코드 emotion.styled 로 수정
